time = raw_input("What is your favorite number?")
items = raw_input("What is the item on your right?")
name = raw_input("What's your name?")
scream = raw_input("What do you yell when you want to scream?")
print scream.upper()
action = raw_input("What would you do if you got scared?")
print "It is %s in the morning and %s was sleeping. You pick up a %s and yell "%s!" %s was so scared, that they started to %s" %(time, name.upper()[0], item, scream.upper(), name, action)
